name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 1 1"
  push:
    branches: "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        if: "!contains(github.event.head_commit.message, '[Skip GitHub Action]')"
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          user: moncefplastin07
          plugin_pagespeed: yes
          plugin_lines: yes
